export interface BlogCategoryInfo {
  slug: string;
  label: string;
}

export const blogCategories: BlogCategoryInfo[] = [
  { slug: "formalites", label: "Formalités & préparatifs avant le départ" },
  { slug: "logistique-transit", label: "Logistique en transit (aéroport & avion)" },
  { slug: "spiritualite", label: "Spiritualité, rites & pratique religieuse" },
  { slug: "programme", label: "Programme & organisation du voyage" },
  { slug: "vie-pratique", label: "Vie pratique sur place" },
  { slug: "decouvrir-mecque", label: "Découvrir La Mecque" },
  { slug: "decouvrir-medine", label: "Découvrir Médine" },
];

export interface BlogPostCategoryMap {
  slug: string;
  categorySlug: string;
}

export const blogPostCategories: BlogPostCategoryMap[] = [
  { slug: "hajj-assurance-formalites-sanitaires", categorySlug: "formalites" },
  { slug: "hajj-centres-vaccin-abidjan", categorySlug: "formalites" },
  { slug: "omra-checklist-valise", categorySlug: "formalites" },
  { slug: "hajj-checklist-bagages-formalites", categorySlug: "formalites" },
  { slug: "hajj-documents-agence", categorySlug: "formalites" },
  { slug: "omra-assurance-voyage", categorySlug: "formalites" },
  { slug: "omra-indispensables", categorySlug: "formalites" },
  { slug: "hajj-medicaments-bagages", categorySlug: "formalites" },
  { slug: "hajj-passeport-documents", categorySlug: "formalites" },
  { slug: "hajj-vaccins-formalites", categorySlug: "formalites" },
  { slug: "hajj-visa-omra-hajj", categorySlug: "formalites" },
  { slug: "hajj-ablutions-avion", categorySlug: "logistique-transit" },
  { slug: "hajj-priere-avion", categorySlug: "logistique-transit" },
  { slug: "hajj-miqat-avion", categorySlug: "logistique-transit" },
  { slug: "hajj-ihram-aeroport", categorySlug: "logistique-transit" },
  { slug: "omra-conseils-joumoua", categorySlug: "spiritualite" },
  { slug: "omra-deces-procedures", categorySlug: "spiritualite" },
  { slug: "omra-miqat", categorySlug: "spiritualite" },
  { slug: "omra-invocations-douas", categorySlug: "spiritualite" },
  { slug: "omra-rites", categorySlug: "spiritualite" },
  { slug: "omra-programme-type", categorySlug: "programme" },
  { slug: "omra-jour-apres-jour", categorySlug: "programme" },
  { slug: "omra-blanchisserie", categorySlug: "vie-pratique" },
  { slug: "omra-enfants-famille", categorySlug: "vie-pratique" },
  { slug: "omra-gastronomie-hedjaz", categorySlug: "vie-pratique" },
  { slug: "omra-pmr-accessibilite", categorySlug: "vie-pratique" },
  { slug: "omra-shopping", categorySlug: "vie-pratique" },
  { slug: "omra-sante", categorySlug: "vie-pratique" },
  { slug: "omra-mecque-lieu-ain-zoubayda", categorySlug: "decouvrir-mecque" },
  { slug: "omra-decouvrir-la-mecque", categorySlug: "decouvrir-mecque" },
  { slug: "omra-mecque-lieu-jabal-thawr", categorySlug: "decouvrir-mecque" },
  { slug: "omra-mecque-lieu-jabal-al-nour", categorySlug: "decouvrir-mecque" },
  { slug: "omra-mecque-lieu-usine-kiswa", categorySlug: "decouvrir-mecque" },
  { slug: "omra-mecque-lieu-masjid-al-haram-kaaba", categorySlug: "decouvrir-mecque" },
  { slug: "mecque-004-plein-air", categorySlug: "decouvrir-mecque" },
  { slug: "mecque-003-enfants", categorySlug: "decouvrir-mecque" },
  { slug: "mecque-005-petits-budgets", categorySlug: "decouvrir-mecque" },
  { slug: "mecque-002-incontournables", categorySlug: "decouvrir-mecque" },
  { slug: "mecque-006-musees-expositions", categorySlug: "decouvrir-mecque" },
  { slug: "omra-mecque-lieu-tour-horloge", categorySlug: "decouvrir-mecque" },
  { slug: "omra-mecque-lieu-mosquee-aicha", categorySlug: "decouvrir-mecque" },
  { slug: "omra-mecque-lieu-mosquee-djinns", categorySlug: "decouvrir-mecque" },
  { slug: "omra-mecque-lieu-musee-saint-coran", categorySlug: "decouvrir-mecque" },
  { slug: "omra-mecque-lieu-musee-international-biographie-mecque", categorySlug: "decouvrir-mecque" },
  { slug: "omra-mecque-lieu-mont-arafat", categorySlug: "decouvrir-mecque" },
  { slug: "omra-mecque-lieu-musee-wahy", categorySlug: "decouvrir-mecque" },
  { slug: "omra-mecque-lieu-mina", categorySlug: "decouvrir-mecque" },
  { slug: "omra-mecque-lieu-muzdalifah", categorySlug: "decouvrir-mecque" },
  { slug: "mecque-001-attractions", categorySlug: "decouvrir-mecque" },
  { slug: "omra-mecque-lieu-safa-et-marwa", categorySlug: "decouvrir-mecque" },
  { slug: "medine-003-plein-air", categorySlug: "decouvrir-medine" },
  { slug: "medine-002-enfants", categorySlug: "decouvrir-medine" },
  { slug: "medine-001-incontournables", categorySlug: "decouvrir-medine" },
  { slug: "medine-004-musees-expositions", categorySlug: "decouvrir-medine" },
  { slug: "omra-decouvrir-medine", categorySlug: "decouvrir-medine" },
  { slug: "omra-medine-lieu-elephant-rock", categorySlug: "decouvrir-medine" },
  { slug: "omra-medine-lieu-hegra", categorySlug: "decouvrir-medine" },
  { slug: "omra-medine-lieu-jabal-ikmah", categorySlug: "decouvrir-medine" },
  { slug: "omra-medine-lieu-mosquee-du-prophete", categorySlug: "decouvrir-medine" },
  { slug: "omra-medine-lieu-gare-hedjaz", categorySlug: "decouvrir-medine" },
  { slug: "omra-medine-lieu-mosquee-al-qiblatayn", categorySlug: "decouvrir-medine" },
  { slug: "omra-medine-lieu-mosquee-de-quba", categorySlug: "decouvrir-medine" },
  { slug: "omra-medine-lieu-vieille-ville-medine", categorySlug: "decouvrir-medine" },
  { slug: "omra-medine-lieu-musee-international-biographie-medine", categorySlug: "decouvrir-medine" },
  { slug: "omra-medine-lieu-cimetiere-al-baqi", categorySlug: "decouvrir-medine" },
  { slug: "omra-medine-lieu-mont-ouhud", categorySlug: "decouvrir-medine" },
  { slug: "omra-medine-lieu-musee-dar-al-madinah", categorySlug: "decouvrir-medine" },
  { slug: "omra-medine-lieu-puits-de-ghars", categorySlug: "decouvrir-medine" },
  { slug: "omra-medine-lieu-sept-mosquees", categorySlug: "decouvrir-medine" },
  { slug: "omra-medine-lieu-maraya", categorySlug: "decouvrir-medine" },
];
