export interface FaqItem {
  slug: string;
  articleSlug: string;
  categorySlug: string;
  question: string;
  answer: string;
}

export const faqItems: FaqItem[] = [
  {
    slug: "hajj-assurance-formalites-sanitaires",
    articleSlug: "hajj-assurance-formalites-sanitaires",
    categorySlug: "formalites",
    question: "L'assurance santé est-elle obligatoire pour la Omra ou le Hajj ?",
    answer: "Oui : une assurance santé est intégrée au cadre de couverture des pèlerins en Arabie saoudite, avec une prise en charge des situations d'urgence selon la police applicable. Cette couverture n'équivaut toutefois pas toujours à une assurance voyage complète : une assurance complémentaire peut rester utile pour l'annulation, les bagages, le transit ou des garanties étendues. Les autorités saoudiennes proposent d'ailleurs un service d'information permettant de vérifier sa couverture avant le départ.",
  },
  {
    slug: "hajj-centres-vaccin-abidjan",
    articleSlug: "hajj-centres-vaccin-abidjan",
    categorySlug: "formalites",
    question: "Où faire le vaccin ACWY à Abidjan ?",
    answer: "L'Institut National d'Hygiène Publique (INHP) est l'organisme de référence pour la vaccination internationale en Côte d'Ivoire, avec un siège à Treichville et plusieurs antennes à Abidjan : Gonzagueville, Cocody-Bingerville, Yopougon Toits-Rouges et Abobo-Baoulé. Le vaccin méningite ACWY135 figure bien dans l'offre vaccinale proposée par l'INHP.",
  },
  {
    slug: "hajj-checklist-bagages-formalites",
    articleSlug: "hajj-checklist-bagages-formalites",
    categorySlug: "formalites",
    question: "Quels sont les indispensables à garder en bagage cabine ?",
    answer: "Le passeport, le visa, les billets, les certificats de vaccination, l'assurance, les médicaments essentiels, l'argent, le téléphone et les copies des documents doivent impérativement rester dans le bagage cabine. Avant de fermer sa valise, il convient aussi de vérifier la conformité des médicaments, les vêtements adaptés, les accessoires d'ihram, ainsi que les objets interdits ou restreints par les douanes saoudiennes.",
  },
  {
    slug: "hajj-documents-agence",
    articleSlug: "hajj-documents-agence",
    categorySlug: "formalites",
    question: "Quels documents faut-il demander à son agence de voyage ?",
    answer: "Le pèlerin doit obtenir un contrat clair, les reçus de paiement, le programme du séjour, les billets, les confirmations d'hôtel, les coordonnées du guide et les documents liés au visa. Il est aussi recommandé de vérifier la licence de l'agence : en Côte d'Ivoire, l'activité d'agence de voyages s'inscrit dans un cadre d'agrément qui permet au client de vérifier le sérieux de l'opérateur. Un programme écrit reste indispensable, car il fixe noir sur blanc les hôtels, les transports, les dates et les prestations incluses, ce qui limite les litiges.",
  },
  {
    slug: "hajj-medicaments-bagages",
    articleSlug: "hajj-medicaments-bagages",
    categorySlug: "formalites",
    question: "Peut-on voyager avec ses médicaments personnels ?",
    answer: "Oui, à condition qu'ils soient destinés à un usage personnel, conservés dans leur emballage d'origine et, si nécessaire, accompagnés d'une ordonnance ou d'un certificat médical. Une attention particulière est requise pour les médicaments contenant des substances contrôlées — certains antidouleurs, anxiolytiques, somnifères ou traitements neurologiques — qui peuvent nécessiter une autorisation préalable. Il faut en revanche éviter tout comprimé non identifié, tout produit sans boîte d'origine ou toute préparation inconnue, susceptibles d'être interdits ou restreints par la douane saoudienne.",
  },
  {
    slug: "hajj-passeport-documents",
    articleSlug: "hajj-passeport-documents",
    categorySlug: "formalites",
    question: "Quels documents faut-il préparer pour partir ?",
    answer: "Le dossier de départ comprend en général un passeport valide, des photos d'identité, les justificatifs demandés, les réservations de vol et d'hébergement, ainsi que les documents sanitaires requis. Le passeport doit être valide au moins six mois au-delà du séjour, ou à l'entrée sur le territoire saoudien : un passeport proche de l'expiration peut entraîner un refus de visa, voire un refus d'embarquement. Il est également prudent de conserver des copies papier et numériques du passeport, du visa et des documents essentiels, en cas de perte ou de contrôle.",
  },
  {
    slug: "hajj-vaccins-formalites",
    articleSlug: "hajj-vaccins-formalites",
    categorySlug: "formalites",
    question: "Quels vaccins sont exigés pour la Omra ou le Hajj ?",
    answer: "Deux vaccinations sont à prévoir pour un départ depuis la Côte d'Ivoire. Le vaccin contre la méningite ACWY est requis pour tous les pèlerins, selon les exigences sanitaires saoudiennes publiées pour le Hajj et l'Omra, et doit être administré au minimum dix jours avant l'arrivée en Arabie saoudite. La fièvre jaune est également obligatoire : les voyageurs arrivant d'un pays à risque comme la Côte d'Ivoire doivent présenter un certificat international de vaccination, valable à partir du dixième jour après l'injection puis à vie.",
  },
  {
    slug: "hajj-visa-omra-hajj",
    articleSlug: "hajj-visa-omra-hajj",
    categorySlug: "formalites",
    question: "Quelle est la différence entre un visa Omra et un visa Hajj ?",
    answer: "Le visa Omra est destiné au pèlerinage mineur, accompli en dehors de la période du grand pèlerinage, tandis que le visa Hajj concerne exclusivement le grand pèlerinage, pendant sa période spécifique du calendrier hégirien. Le visa Omra ne peut en aucun cas être utilisé pour accomplir le Hajj, qui obéit à des règles, des quotas et une organisation distincts. Sa délivrance dépend d'ailleurs de la saison du Hajj et des procédures publiées pour chaque campagne. Dans tous les cas, le type de visa doit correspondre exactement au projet réel du pèlerin et à la période autorisée.",
  },
  {
    slug: "omra-assurance-voyage",
    articleSlug: "omra-assurance-voyage",
    categorySlug: "formalites",
    question: "Que couvre l'assurance incluse dans le visa Nusuk ?",
    answer: "Le visa donne accès à des soins d'urgence de base sur place, à La Mecque comme à Médine, gérés par des organismes locaux désignés par l'administration saoudienne.",
  },
  {
    slug: "omra-assurance-voyage-1",
    articleSlug: "omra-assurance-voyage",
    categorySlug: "formalites",
    question: "Cette couverture est-elle suffisante ?",
    answer: "Non : elle reste calibrée sur les exigences administratives minimales du visa. Elle ne couvre ni l'annulation de séjour, ni la perte de bagages, ni un rapatriement sanitaire complet en cas de besoin.",
  },
  {
    slug: "omra-assurance-voyage-2",
    articleSlug: "omra-assurance-voyage",
    categorySlug: "formalites",
    question: "Pourquoi souscrire une assurance pour le rapatriement sanitaire ?",
    answer: "En cas de nécessité, le transport médicalisé ou le rapatriement représente des frais réels très élevés, rarement pris en charge sans un contrat spécifique — l'un des principaux arguments en faveur d'une assurance complémentaire.",
  },
  {
    slug: "omra-assurance-voyage-3",
    articleSlug: "omra-assurance-voyage",
    categorySlug: "formalites",
    question: "Suis-je remboursé en cas d'annulation ?",
    answer: "Une assurance complémentaire permet un remboursement en cas d'empêchement majeur survenant avant le départ.",
  },
  {
    slug: "omra-assurance-voyage-4",
    articleSlug: "omra-assurance-voyage",
    categorySlug: "formalites",
    question: "Mes bagages sont-ils couverts en cas de perte ou de vol ?",
    answer: "Une assurance complémentaire permet une indemnisation en cas de perte, de vol ou de détérioration des valises pendant le transport.",
  },
  {
    slug: "omra-assurance-voyage-5",
    articleSlug: "omra-assurance-voyage",
    categorySlug: "formalites",
    question: "Quelles garanties vérifier avant de souscrire ?",
    answer: "Quelques garanties méritent une attention particulière au moment de choisir un contrat : une assistance médicale disponible 24h/24 et 7j/7, le remboursement des frais de santé d'urgence non couverts par le visa de base, et une couverture de responsabilité civile à l'étranger.",
  },
  {
    slug: "omra-checklist-valise",
    articleSlug: "omra-checklist-valise",
    categorySlug: "formalites",
    question: "Quels vêtements emporter ?",
    answer: "Qamis, abaya ou jilbab ; des chaussures confortables ; un pyjama ; un pantacourt ou pantalon court ; des sous-vêtements, t-shirts et débardeurs ; des sandales ; un chapeau, une casquette ou un parapluie.",
  },
  {
    slug: "omra-checklist-valise-1",
    articleSlug: "omra-checklist-valise",
    categorySlug: "formalites",
    question: "Quels accessoires sont utiles ?",
    answer: "Un brumisateur ou petit ventilateur portable ; de la crème solaire ; des épingles à nourrice ; un adaptateur de prise électrique ; un chargeur de téléphone et des écouteurs ; des lunettes de soleil.",
  },
  {
    slug: "omra-checklist-valise-2",
    articleSlug: "omra-checklist-valise",
    categorySlug: "formalites",
    question: "Quels produits d'hygiène prévoir ?",
    answer: "Une trousse de toilette ; du savon ou du gel douche sans parfum (important en état d'ihram) ; du shampoing ; du déodorant ; une brosse à dents et un siwak ; du dentifrice ; une solution hydroalcoolique ; un produit pour la lessive à la main.",
  },
  {
    slug: "omra-indispensables",
    articleSlug: "omra-indispensables",
    categorySlug: "formalites",
    question: "Quels documents et quelle somme d'argent emporter ?",
    answer: "Un passeport ; un titre de séjour, le cas échéant ; de l'argent liquide, en francs CFA ou en riyals saoudiens ; une carte bancaire ; un téléphone portable débloqué tout opérateur.",
  },
  {
    slug: "omra-indispensables-1",
    articleSlug: "omra-indispensables",
    categorySlug: "formalites",
    question: "Que faire si je suis un traitement chronique ?",
    answer: "Pour toute maladie chronique (diabète et autres), il est important de prévoir au moins 15 jours de traitement, si possible en double exemplaire, accompagné de l'ordonnance d'origine. Il est également recommandé de ne pas mettre tous les médicaments dans le même bagage, afin de ne pas se retrouver démuni en cas de perte d'une valise.",
  },
  {
    slug: "omra-indispensables-2",
    articleSlug: "omra-indispensables",
    categorySlug: "formalites",
    question: "Quels médicaments courants emporter ?",
    answer: "Un traitement contre le rhume ; un traitement contre la diarrhée ; un traitement contre le mal des transports ; du paracétamol ; du sérum physiologique ; des pansements ; de quoi traiter les ampoules aux pieds ; un antiseptique.",
  },
  {
    slug: "hajj-ablutions-avion",
    articleSlug: "hajj-ablutions-avion",
    categorySlug: "logistique-transit",
    question: "Faut-il absolument faire ses ablutions dans l'avion ?",
    answer: "Non : le plus simple reste de faire ses ablutions avant l'embarquement, puis de les renouveler seulement si nécessaire pendant le vol. Si un renouvellement s'impose à bord, les ablutions peuvent être réalisées de manière simple et discrète avec très peu d'eau, en veillant à garder l'espace propre et sûr pour les autres passagers.",
  },
  {
    slug: "hajj-ihram-aeroport",
    articleSlug: "hajj-ihram-aeroport",
    categorySlug: "logistique-transit",
    question: "Quand faut-il entrer en ihram pour un vol direct vers La Mecque ?",
    answer: "Le pèlerin qui se rend directement vers La Mecque ne doit en aucun cas dépasser le miqat sans être entré en état d'ihram. Les hommes peuvent tout à fait porter les tissus d'ihram dès l'aéroport, avant l'embarquement, sans pour autant formuler l'intention si le miqat n'a pas encore été atteint. Un point important à retenir : l'aéroport de Djeddah (King Abdulaziz) n'est pas lui-même un miqat, contrairement à une idée reçue.",
  },
  {
    slug: "hajj-miqat-avion",
    articleSlug: "hajj-miqat-avion",
    categorySlug: "logistique-transit",
    question: "Comment savoir que le miqat approche pendant le vol ?",
    answer: "Le moyen le plus fiable reste l'annonce de l'équipage ou la consigne du guide de groupe, en particulier sur les vols liés aux pèlerins. Il ne faut surtout pas attendre l'atterrissage à Djeddah pour entrer en ihram : celui-ci doit être pris avant le franchissement du miqat aérien, si le vol mène directement vers La Mecque, car l'aéroport de Djeddah se trouve déjà à l'intérieur de la zone sacrée.",
  },
  {
    slug: "hajj-priere-avion",
    articleSlug: "hajj-priere-avion",
    categorySlug: "logistique-transit",
    question: "Peut-on prier assis dans l'avion ?",
    answer: "Oui : lorsqu'il est impossible ou dangereux de prier debout, le voyageur prie selon ses capacités, y compris assis, avec des inclinaisons adaptées pour le ruku et le sujood. Il est possible d'attendre l'atterrissage si l'horaire de la prière ne risque pas de se terminer avant l'arrivée ; sinon, il faut prier à bord. Selon l'avis religieux suivi, le voyageur peut également regrouper certaines prières entre elles : Dhuhr avec Asr, et Maghrib avec Isha.",
  },
  {
    slug: "omra-conseils-joumoua",
    articleSlug: "omra-conseils-joumoua",
    categorySlug: "spiritualite",
    question: "Comment bien vivre la prière du vendredi (Joumou'a) pendant la Omra ?",
    answer: "La Joumou'a prend un relief particulier à la Mosquée du Prophète ou à la Masjid al-Haram. Pour bien la préparer : grandes ablutions (ghusl), ongles coupés, vêtements propres, siwak, et parfum pour les hommes. Le jour même, mieux vaut se rendre à la prière le plus tôt possible pour espérer une place à l'intérieur, méditer sur la khotba, lire la sourate Al-Kahf, multiplier les prières sur le Prophète ﷺ et les invocations tout au long de la journée.",
  },
  {
    slug: "omra-conseils-joumoua-1",
    articleSlug: "omra-conseils-joumoua",
    categorySlug: "spiritualite",
    question: "Comment se préparer avant la prière du vendredi ?",
    answer: "Faire ses grandes ablutions (ghusl) ; se couper les ongles ; porter des vêtements propres ; se brosser les dents avec le siwak ; se parfumer — à l'exception des femmes.",
  },
  {
    slug: "omra-conseils-joumoua-2",
    articleSlug: "omra-conseils-joumoua",
    categorySlug: "spiritualite",
    question: "Comment vivre pleinement la journée du vendredi ?",
    answer: "Se rendre à la prière le plus tôt possible, afin d'espérer une place à l'intérieur de la mosquée ; méditer sur la khotba (le sermon) et son message ; lire la sourate Al-Kahf ; multiplier les prières sur le Prophète ﷺ ; faire des invocations (dou'as) tout au long de la journée.",
  },
  {
    slug: "omra-deces-procedures",
    articleSlug: "omra-deces-procedures",
    categorySlug: "spiritualite",
    question: "Que se passe-t-il en cas de décès pendant le pèlerinage ?",
    answer: "Les autorités saoudiennes disposent d'une procédure établie et respectueuse des rites islamiques. Un médecin ou un établissement hospitalier constate le décès ; l'agence de voyage et les proches préviennent le consulat du pays d'origine ; un permis d'inhumer est délivré, le rapatriement du corps n'étant, dans la grande majorité des cas, pas prévu. L'inhumation a lieu sur place — à Jannat al-Mala ou Al-Adl pour La Mecque, à Jannat al-Baqi pour Médine — précédée d'une prière funéraire (Salat al-Janaza) accomplie en assemblée, le plus souvent directement à la Masjid al-Haram ou à la Mosquée du Prophète.",
  },
  {
    slug: "omra-deces-procedures-1",
    articleSlug: "omra-deces-procedures",
    categorySlug: "spiritualite",
    question: "Comment le décès est-il constaté ?",
    answer: "Un médecin assermenté ou un établissement hospitalier local établit le certificat de décès officiel, première étape de la procédure.",
  },
  {
    slug: "omra-deces-procedures-2",
    articleSlug: "omra-deces-procedures",
    categorySlug: "spiritualite",
    question: "Qui prévient le consulat ?",
    answer: "L'agence de voyage et les proches préviennent immédiatement l'ambassade ou le consulat du pays d'origine du défunt, qui accompagne la famille dans les démarches et l'informe de la suite donnée.",
  },
  {
    slug: "omra-deces-procedures-3",
    articleSlug: "omra-deces-procedures",
    categorySlug: "spiritualite",
    question: "Le corps peut-il être rapatrié ?",
    answer: "Les autorités saoudiennes délivrent un permis d'inhumer. Le rapatriement du corps n'est, dans la grande majorité des cas, pas prévu : l'inhumation sur place en Arabie saoudite constitue la règle générale.",
  },
  {
    slug: "omra-deces-procedures-4",
    articleSlug: "omra-deces-procedures",
    categorySlug: "spiritualite",
    question: "Où le défunt est-il inhumé ?",
    answer: "À La Mecque, l'inhumation a généralement lieu au cimetière de Jannat al-Mala ou au cimetière Al-Adl. À Médine, c'est le cimetière de Jannat al-Baqi qui accueille le plus souvent les défunts, ou un autre cimetière de la ville selon les places disponibles.",
  },
  {
    slug: "omra-deces-procedures-5",
    articleSlug: "omra-deces-procedures",
    categorySlug: "spiritualite",
    question: "Comment se déroule la prière funéraire ?",
    answer: "La prière funéraire (Salat al-Janaza) est accomplie en assemblée, le plus souvent directement à la Masjid al-Haram à La Mecque ou à la Mosquée du Prophète à Médine — un dernier hommage collectif rendu au défunt par l'ensemble des fidèles présents, avant l'inhumation.",
  },
  {
    slug: "omra-invocations-douas",
    articleSlug: "omra-invocations-douas",
    categorySlug: "spiritualite",
    question: "Quelles sont les invocations (douas) à réciter pendant la Omra ?",
    answer: "Chaque étape de la Omra est associée à des invocations spécifiques enseignées par le Prophète ﷺ, qu'il reste toutefois permis de compléter par ses propres mots. Au miqat, le pèlerin formule son intention puis récite la Talbiyah. En entrant dans la Mosquée Sacrée, une invocation dédiée est prononcée. Pendant le tawaf, une formule coranique est récitée entre le Coin yéménite et la Pierre noire. D'autres invocations accompagnent la prière derrière la Station d'Ibrahim, la consommation de l'eau de Zamzam, et le sa'i entre Safa et Marwah.",
  },
  {
    slug: "omra-invocations-douas-1",
    articleSlug: "omra-invocations-douas",
    categorySlug: "spiritualite",
    question: "Que dire au Miqat ?",
    answer: "Au moment de franchir le miqat (en vol ou à la mosquée Aïcha), le pèlerin formule d'abord son intention :",
  },
  {
    slug: "omra-invocations-douas-2",
    articleSlug: "omra-invocations-douas",
    categorySlug: "spiritualite",
    question: "Que dire en entrant dans la Mosquée Sacrée (Al-Masjid al-Haram) ?",
    answer: "Le pèlerin entre du pied droit et dit :",
  },
  {
    slug: "omra-invocations-douas-3",
    articleSlug: "omra-invocations-douas",
    categorySlug: "spiritualite",
    question: "Que dire pendant le tawaf (les sept tours de la Kaaba) ?",
    answer: "Au début de chaque tour, devant la Pierre noire, le pèlerin lève la main droite vers elle et dit :",
  },
  {
    slug: "omra-invocations-douas-4",
    articleSlug: "omra-invocations-douas",
    categorySlug: "spiritualite",
    question: "Que dire derrière la Station d'Ibrahim (Maqam Ibrahim) ?",
    answer: "Après le tawaf, en se dirigeant vers la station pour y prier deux unités, le pèlerin récite ce verset :",
  },
  {
    slug: "omra-invocations-douas-5",
    articleSlug: "omra-invocations-douas",
    categorySlug: "spiritualite",
    question: "Que dire en buvant l'eau de Zamzam ?",
    answer: "Le Prophète ﷺ a enseigné que l'eau de Zamzam est bénéfique pour ce pourquoi elle est bue. Le pèlerin peut ainsi dire :",
  },
  {
    slug: "omra-invocations-douas-6",
    articleSlug: "omra-invocations-douas",
    categorySlug: "spiritualite",
    question: "Que dire pendant le sa'i (entre Safa et Marwah) ?",
    answer: "En approchant du mont Safa pour commencer le sa'i, le pèlerin récite ce verset :",
  },
  {
    slug: "omra-miqat",
    articleSlug: "omra-miqat",
    categorySlug: "spiritualite",
    question: "Qu'est-ce que le Miqat et où le prendre ?",
    answer: "Le miqat est le point géographique où le pèlerin doit formuler son intention (niyya) et revêtir l'ihram, avant d'entrer dans l'enceinte sacrée de La Mecque. Cinq lieux de miqat existent selon la direction d'arrivée (Dhul-Hulayfah, Al-Juhfah, Qarn al-Manazil, Yalamlam, Dhat 'Irq). Pour un vol, le miqat est généralement survolé, avec une annonce de l'équipage quelques minutes avant. Depuis Abidjan, le miqat dépend du premier point d'atterrissage : Médine (miqat pris ensuite sur la route vers La Mecque) ou Djeddah (miqat survolé en vol). La mosquée Aïcha, plus proche de La Mecque, sert de miqat pour une Omra supplémentaire pendant le séjour.",
  },
  {
    slug: "omra-miqat-1",
    articleSlug: "omra-miqat",
    categorySlug: "spiritualite",
    question: "Quels sont les cinq lieux de Miqat ?",
    answer: "Dhul-Hulayfah (Abyar Ali), pour les pèlerins venant de Médine ou de cette direction, à environ 420 km de La Mecque ; Al-Juhfah, près de Rabigh, pour les pèlerins venant du Maghreb, d'Europe, d'Amérique ou de la région du Cham (Syrie, Liban...) ; Qarn al-Manazil (Al-Sayl al-Kabir), pour les voyageurs arrivant de Riyad, du Najd ou de l'Est ; Yalamlam, pour les pèlerins venant du Yémen ou du sud ; Dhat 'Irq, pour les pèlerins venant d'Irak, d'Iran et de l'Est.",
  },
  {
    slug: "omra-miqat-2",
    articleSlug: "omra-miqat",
    categorySlug: "spiritualite",
    question: "Comment procéder si le Miqat est survolé en avion ?",
    answer: "Lorsque le vol se rend directement à Djeddah ou à Médine, l'appareil survole généralement la zone du miqat (le plus souvent Al-Juhfah, ou une zone parallèle au-dessus de la mer ou de terres proches). Le commandant de bord ou l'équipage diffuse en général une annonce quelques minutes avant ce survol. Il est recommandé de revêtir la tenue d'ihram dès l'aéroport de départ ou dans l'avion, puis de formuler l'intention à voix haute (« Labbayka Allâhumma 'Umratan ») au moment précis de l'annonce en vol.",
  },
  {
    slug: "omra-miqat-3",
    articleSlug: "omra-miqat",
    categorySlug: "spiritualite",
    question: "Que faire si j'atterris d'abord à Médine (en partant d'Abidjan) ?",
    answer: "Aucun miqat n'est survolé pendant le vol : le voyage se fait en vêtements civils, jusqu'à l'hôtel à Médine. Ce n'est qu'après le séjour à Médine, sur la route vers La Mecque, que le pèlerin s'arrête au miqat de Dhul-Hulayfah (Abyar Ali) pour revêtir l'ihram, prier et formuler son intention avant de poursuivre vers La Mecque.",
  },
  {
    slug: "omra-miqat-4",
    articleSlug: "omra-miqat",
    categorySlug: "spiritualite",
    question: "Que faire si j'atterris directement à Djeddah (en partant d'Abidjan) ?",
    answer: "Le miqat se trouve alors en plein vol : le vol de correspondance vers Djeddah survole la limite du miqat, généralement Al-Juhfah ou une zone parallèle, avant l'atterrissage. Il convient de revêtir l'ihram pendant l'escale (par exemple à Casablanca, Tunis ou Istanbul) ou peu après le décollage du second vol. Le commandant de bord annonce en général le miqat 20 à 30 minutes avant de le survoler : c'est à cette annonce, et à ce moment précis, qu'il faut formuler l'intention à voix haute — ni avant, ni après, car l'aéroport de Djeddah se trouve déjà à l'intérieur de la zone sacrée.",
  },
  {
    slug: "omra-miqat-5",
    articleSlug: "omra-miqat",
    categorySlug: "spiritualite",
    question: "Comment faire une Omra supplémentaire avec la mosquée Aïcha ?",
    answer: "La mosquée Aïcha (Masjid al-Tan'im), aussi appelée Miqat al-Tan'im, est le point de sacralisation le plus proche de La Mecque — à environ 7,5 km au nord de la Kaaba. Elle sert exclusivement de miqat aux pèlerins déjà présents à La Mecque et souhaitant accomplir une Omra supplémentaire pendant leur séjour. Depuis l'hôtel, un taxi ou un bus permet de rejoindre la mosquée, ce qui fait sortir des limites sacrées du Haram. Sur place, de grandes installations permettent de se doucher, de faire ses ablutions et de revêtir l'ihram. Le pèlerin accomplit ensuite deux unités de prière s'il le souhaite, puis formule son intention à voix haute (« Labbayka Allâhumma 'Umratan »), avant de reprendre un transport vers la Masjid al-Haram en récitant la Talbiyah pour commencer le tawaf et le sa'i. Point important : la mosquée Aïcha ne peut pas être utilisée pour une première Omra en arrivant d'Abidjan — la première intention doit obligatoirement être prise au miqat survolé pendant le vol, ou à Médine (Dhul-Hulayfah), selon l'itinéraire emprunté.",
  },
  {
    slug: "omra-rites",
    articleSlug: "omra-rites",
    categorySlug: "spiritualite",
    question: "Quels sont les rites de la Omra ?",
    answer: "La Omra se déroule en quatre étapes : l'ihram (sacralisation, avec ablutions, tenue spécifique et formulation de l'intention au miqat) ; le tawaf, sept tours autour de la Kaaba dans le sens inverse des aiguilles d'une montre ; le sa'i, sept trajets entre les collines de Safa et Marwa ; et enfin la désacralisation (at-tahalul), marquée par le rasage ou la coupe des cheveux.",
  },
  {
    slug: "omra-rites-1",
    articleSlug: "omra-rites",
    categorySlug: "spiritualite",
    question: "Qu'est-ce que l'ihram ?",
    answer: "Le pèlerin commence par accomplir ses grandes ablutions (ghusl) et se pare de propreté. Il revêt ensuite la tenue de sacralisation : deux pièces d'étoffe blanche non cousues pour l'homme, une tenue ample et décente couvrant le corps pour la femme. C'est au niveau du miqat, le point de passage obligatoire, que le pèlerin formule son intention (niyya) de la Omra, avant de réciter la Talbiyya — à voix haute pour les hommes, à voix basse pour les femmes — tout au long du trajet vers La Mecque.",
  },
  {
    slug: "omra-rites-2",
    articleSlug: "omra-rites",
    categorySlug: "spiritualite",
    question: "Qu'est-ce que le tawaf ?",
    answer: "Une fois à la Mosquée Sacrée, le pèlerin cesse de réciter la Talbiyya et accomplit sept tours autour de la Kaaba, dans le sens inverse des aiguilles d'une montre, en débutant et en saluant la Pierre noire à chaque tour. Les hommes marchent d'un pas vif lors des trois premiers tours, puis à rythme normal pour les quatre derniers. Il est recommandé, si possible, de prier deux unités derrière la Station d'Abraham (Maqam Ibrahim), puis de boire de l'eau de Zamzam en formulant des invocations.",
  },
  {
    slug: "omra-rites-3",
    articleSlug: "omra-rites",
    categorySlug: "spiritualite",
    question: "Qu'est-ce que le sa'i ?",
    answer: "Le pèlerin se rend ensuite sur la colline de Safa pour entamer le sa'i : sept trajets aller-retour entre les monts de Safa et Marwa, un aller comptant pour un trajet et un retour pour un autre. Les hommes accélèrent le pas dans la zone balisée entre les deux repères verts, tout en multipliant les invocations.",
  },
  {
    slug: "omra-rites-4",
    articleSlug: "omra-rites",
    categorySlug: "spiritualite",
    question: "Qu'est-ce que la désacralisation (at-tahalul) ?",
    answer: "La Omra s'achève par la désacralisation : les hommes se rasent entièrement la tête ou raccourcissent leurs cheveux — le rasage complet étant recommandé — tandis que les femmes coupent l'équivalent d'une phalange de doigt, environ 1 à 2 cm, à l'extrémité de leurs cheveux. Ce geste marque la fin du rituel et la sortie de l'état d'ihram.",
  },
  {
    slug: "omra-jour-apres-jour",
    articleSlug: "omra-jour-apres-jour",
    categorySlug: "programme",
    question: "Comment se déroule un séjour Omra avec SIRA Voyages, jour après jour ?",
    answer: "Un séjour Omra avec SIRA Voyages se déroule sur environ dix jours, partagés entre Médine et La Mecque, avec un guide présent du premier au dernier jour. Il débute par quelques jours de recueillement à Médine, avec des cours sur les mérites de la ville et les rites de la Omra, puis des visites guidées des lieux emblématiques. Le groupe rejoint ensuite La Mecque pour accomplir les rites de la Omra ensemble, avant plusieurs jours de temps libre consacrés à la prière et au recueillement à la Masjid al-Haram. Le séjour s'achève par une dernière prière du vendredi et le retour vers Abidjan, avec un accompagnement continu (cours quotidiens, assistance, conseils pratiques) tout au long du voyage.",
  },
  {
    slug: "omra-programme-type",
    articleSlug: "omra-programme-type",
    categorySlug: "programme",
    question: "Comment se déroule le programme type de la Omra avec SIRA Voyages (10 jours) ?",
    answer: "Le séjour Omra de SIRA Voyages se déroule sur dix jours, partagés entre Médine et La Mecque, avec un guide dédié présent du premier au dernier jour. Il alterne temps collectifs (cours, visites accompagnées, accomplissement des rites en groupe) et temps libre, incluant l'hébergement, le transport terrestre entre les deux villes et une assistance joignable tout au long du séjour. Cette trame type peut ensuite être complétée par l'ensemble des contenus pratiques et découvertes préparés pour le site SIRA Voyages.",
  },
  {
    slug: "omra-blanchisserie",
    articleSlug: "omra-blanchisserie",
    categorySlug: "vie-pratique",
    question: "Comment faire laver son linge pendant son séjour Omra ?",
    answer: "Deux options s'offrent aux pèlerins à La Mecque comme à Médine. La plupart des hôtels proposent un service de pressing et de lavage au kilo directement à la réception, avec récupération et remise du linge en chambre. Des blanchisseries locales indépendantes, avec ramassage et livraison le jour même, existent également — pour un tarif souvent plus avantageux qu'à l'hôtel, autour de 10 à 12 riyals saoudiens le kilo. Leurs coordonnées évoluent régulièrement : mieux vaut vérifier sur place ou se renseigner auprès de son guide SIRA Voyages.",
  },
  {
    slug: "omra-blanchisserie-1",
    articleSlug: "omra-blanchisserie",
    categorySlug: "vie-pratique",
    question: "Puis-je faire laver mon linge à l'hôtel ?",
    answer: "Oui : il suffit de s'adresser directement à la réception. La plupart des hôtels de La Mecque et de Médine proposent un service de pressing ainsi qu'un lavage au kilo, avec récupération et remise du linge en chambre.",
  },
  {
    slug: "omra-blanchisserie-2",
    articleSlug: "omra-blanchisserie",
    categorySlug: "vie-pratique",
    question: "Existe-t-il des blanchisseries locales avec livraison ?",
    answer: "Oui, des prestataires indépendants opèrent dans les deux villes, avec ramassage et livraison le jour même. Parmi ceux mentionnés par les pèlerins : Wissam à Médine et Ashraf Ali à La Mecque, pour un tarif indicatif d'environ 10 à 12 riyals saoudiens par kilo. Ces services peuvent revenir moins chers que la conciergerie de l'hôtel, mais leurs coordonnées et disponibilités évoluent — à vérifier sur place ou auprès de votre guide SIRA VOYAGES avant de faire appel à l'un d'eux.",
  },
  {
    slug: "omra-enfants-famille",
    articleSlug: "omra-enfants-famille",
    categorySlug: "vie-pratique",
    question: "Peut-on emmener ses enfants en Omra ?",
    answer: "Oui, et les infrastructures des deux Saintes Mosquées ont été pensées pour faciliter le voyage en famille. Chaque enfant doit disposer de son propre passeport et visa. L'accès à la Rawdah à Médine nécessite un permis Nusuk à partir de 5 ans, tandis que le Hajj reste généralement réservé aux enfants ayant atteint la puberté. Des garderies existent à La Mecque (dont une au sein même de la Masjid al-Haram) et à Médine. Les poussettes sont interdites sur le Mataf : le portage en écharpe est indispensable pour le tawaf, et un bracelet d'identification est recommandé pour chaque enfant.",
  },
  {
    slug: "omra-enfants-famille-1",
    articleSlug: "omra-enfants-famille",
    categorySlug: "vie-pratique",
    question: "Un enfant a-t-il besoin de son propre passeport et visa ?",
    answer: "Oui, chaque enfant, y compris les nourrissons, doit disposer de son propre passeport ainsi que d'un visa Omra ou Hajj en cours de validité — aucune exception, quel que soit l'âge.",
  },
  {
    slug: "omra-enfants-famille-2",
    articleSlug: "omra-enfants-famille",
    categorySlug: "vie-pratique",
    question: "Comment un enfant peut-il accéder à la Rawdah Sharifa à Médine ?",
    answer: "L'accès à la Rawdah Sharifa (le « jardin du paradis » de la Mosquée du Prophète) nécessite désormais un permis délivré via l'application Nusuk, disponible uniquement à partir de 5 ans. En dessous de cet âge, l'accès à cet espace précis n'est pas prévu par le système de réservation.",
  },
  {
    slug: "omra-enfants-famille-3",
    articleSlug: "omra-enfants-famille",
    categorySlug: "vie-pratique",
    question: "À partir de quel âge un enfant peut-il faire le Hajj ?",
    answer: "Si la Omra reste accessible à tout âge, les autorités saoudiennes restreignent généralement l'accès au grand pèlerinage du Hajj aux enfants ayant atteint la puberté — souvent fixé autour de 12 ans — en raison de la densité de la foule et de la complexité des rites sur plusieurs jours.",
  },
  {
    slug: "omra-enfants-famille-4",
    articleSlug: "omra-enfants-famille",
    categorySlug: "vie-pratique",
    question: "Existe-t-il des garderies à La Mecque ?",
    answer: "Oui : la Masjid al-Haram dispose d'une crèche et d'une aire de jeux intérieures, capables d'accueillir environ 1 500 enfants par jour. Des garderies privées qualifiées, comme la garderie Sandwich, sont également installées au 2e étage des centres commerciaux de la Tour de l'Horloge, à proximité immédiate du Haram.",
  },
  {
    slug: "omra-enfants-famille-5",
    articleSlug: "omra-enfants-famille",
    categorySlug: "vie-pratique",
    question: "Existe-t-il une garderie à Médine ?",
    answer: "Oui, une garderie officielle est installée à l'extérieur de la Mosquée du Prophète, près de la porte 365 — une option pratique pour les parents souhaitant se rendre à la mosquée sans les tout-petits.",
  },
  {
    slug: "omra-enfants-famille-6",
    articleSlug: "omra-enfants-famille",
    categorySlug: "vie-pratique",
    question: "Un enfant doit-il être en état d'ihram ?",
    answer: "Un enfant en bas âge non mis en état d'ihram n'annule en rien les rites accomplis par ses parents. Il est tout à fait autorisé de porter son enfant pendant le tawaf.",
  },
  {
    slug: "omra-enfants-famille-7",
    articleSlug: "omra-enfants-famille",
    categorySlug: "vie-pratique",
    question: "Poussette ou porte-bébé ?",
    answer: "Les poussettes sont strictement interdites sur le Mataf, l'esplanade qui entoure directement la Kaaba : le portage en écharpe ou en porte-bébé physiologique est donc indispensable pour accomplir le tawaf avec un jeune enfant. La poussette reste en revanche utile à l'extérieur de cette zone, ou pour le trajet entre l'hôtel et la mosquée.",
  },
  {
    slug: "omra-enfants-famille-8",
    articleSlug: "omra-enfants-famille",
    categorySlug: "vie-pratique",
    question: "Comment assurer la sécurité d'un enfant dans la foule ?",
    answer: "Compte tenu de l'affluence, il est fortement recommandé d'équiper chaque enfant d'un bracelet d'identification mentionnant son nom, un numéro de téléphone joignable (avec indicatif international) et le nom de l'hôtel. Des bornes dédiées à la fabrication de ces bracelets sont installées près des escalators menant au Haram.",
  },
  {
    slug: "omra-gastronomie-hedjaz",
    articleSlug: "omra-gastronomie-hedjaz",
    categorySlug: "vie-pratique",
    question: "Quelles sont les spécialités culinaires à découvrir pendant la Omra ?",
    answer: "Le Hedjaz, région qui englobe La Mecque et Médine, offre une cuisine généreuse façonnée par des siècles de passage de pèlerins. Parmi les incontournables : le saleeg, riz crémeux au poulet ; l'aish bil lahm, spécialité mecquoise à la viande hachée ; le kabsa et le mandi, plats emblématiques d'Arabie saoudite ; les dattes Ajwa et Safawi de Médine ; la menthe locale qui parfume le thé ; la harissa (harees), préparation copieuse de blé et de viande ; le mutabbaq et le samboussek, en-cas populaires ; et Al Baik, la chaîne de poulet frit devenue une institution nationale.",
  },
  {
    slug: "omra-pmr-accessibilite",
    articleSlug: "omra-pmr-accessibilite",
    categorySlug: "vie-pratique",
    question: "La Omra est-elle accessible aux personnes malades ou à mobilité réduite ?",
    answer: "Oui : les infrastructures saoudiennes autour des deux Saintes Mosquées permettent d'accueillir les pèlerins malades ou en situation de handicap. Location de fauteuils roulants et de voiturettes, cheminements adaptés, assistance médicale sur place et formules de voyage spécifiques facilitent l'accomplissement des rites. Lorsque le déplacement est réellement impossible, la jurisprudence islamique prévoit l'accomplissement du Hajj ou de la Omra par procuration (Al-Badal), confié à un mandataire de confiance.",
  },
  {
    slug: "omra-pmr-accessibilite-1",
    articleSlug: "omra-pmr-accessibilite",
    categorySlug: "vie-pratique",
    question: "Peut-on louer un fauteuil roulant ou une voiturette sur place ?",
    answer: "Oui : des services officiels de location de fauteuils roulants — manuels ou électriques — ainsi que des voiturettes sont disponibles aux abords des deux Saintes Mosquées, pour faciliter les circumambulations autour de la Kaaba (tawaf) comme les allers-retours entre Safa et Marwa (sa'i), deux rituels qui impliquent normalement une marche prolongée.",
  },
  {
    slug: "omra-pmr-accessibilite-2",
    articleSlug: "omra-pmr-accessibilite",
    categorySlug: "vie-pratique",
    question: "Les lieux saints sont-ils accessibles aux personnes à mobilité réduite ?",
    answer: "Oui : cheminements spécifiques, portes élargies, pentes douces et ascenseurs dédiés permettent aux pèlerins à mobilité réduite de circuler à l'écart des zones de forte affluence, aussi bien à la Masjid al-Haram qu'à la Mosquée du Prophète.",
  },
  {
    slug: "omra-pmr-accessibilite-3",
    articleSlug: "omra-pmr-accessibilite",
    categorySlug: "vie-pratique",
    question: "Y a-t-il une assistance médicale sur place en cas de besoin ?",
    answer: "Oui : le système de santé saoudien déploie des cliniques d'urgence et des unités mobiles autour des lieux saints, permettant une prise en charge rapide des pèlerins les plus vulnérables en cas de besoin.",
  },
  {
    slug: "omra-pmr-accessibilite-4",
    articleSlug: "omra-pmr-accessibilite",
    categorySlug: "vie-pratique",
    question: "Existe-t-il des formules de voyage adaptées aux personnes à mobilité réduite ?",
    answer: "Certaines agences proposent des formules pensées spécifiquement pour les personnes à mobilité réduite : rythme de visite plus flexible, hébergement proche des esplanades et équipé en conséquence, personnel dédié à l'accompagnement — autant d'éléments à anticiper en amont du séjour.",
  },
  {
    slug: "omra-pmr-accessibilite-5",
    articleSlug: "omra-pmr-accessibilite",
    categorySlug: "vie-pratique",
    question: "Des associations peuvent-elles accompagner les pèlerins fragilisés ?",
    answer: "Oui, dans certains cas : des organismes à vocation humanitaire et solidaire interviennent pour accompagner sur le plan médico-social et logistique les pèlerins les plus fragilisés ou porteurs de handicaps lourds.",
  },
  {
    slug: "omra-pmr-accessibilite-6",
    articleSlug: "omra-pmr-accessibilite",
    categorySlug: "vie-pratique",
    question: "Que faire si le voyage est physiquement impossible ?",
    answer: "Lorsque l'état de santé, physique ou mental, rend le déplacement réellement impossible ou dangereux, la jurisprudence islamique prévoit une solution : l'accomplissement du Hajj ou de la Omra par procuration, appelé Al-Badal. Un mandataire qualifié et de confiance accomplit alors les rites au nom de la personne empêchée, lui permettant de s'acquitter de cette obligation ou de ce vœu malgré son impossibilité physique de se rendre sur place.",
  },
  {
    slug: "omra-sante",
    articleSlug: "omra-sante",
    categorySlug: "vie-pratique",
    question: "Comment se soigner pendant son séjour Omra ?",
    answer: "L'Arabie saoudite a développé, autour des lieux saints, un système de santé dense et accessible. Des cliniques de proximité prennent en charge malaises et déshydratation ; des établissements spécialisés assurent soins intensifs et interventions chirurgicales 24h/24 ; les pharmacies sont présentes à chaque coin de rue. Il est recommandé de boire régulièrement de l'eau, d'emporter ses ordonnances traduites et ses médicaments habituels, ainsi qu'un désinfectant sans parfum. Le 997 est le numéro d'urgence médicale en Arabie saoudite.",
  },
  {
    slug: "omra-sante-1",
    articleSlug: "omra-sante",
    categorySlug: "vie-pratique",
    question: "Où trouver une clinique en cas de malaise ?",
    answer: "Des cliniques de proximité sont situées à l'intérieur et aux abords des esplanades du Haram à La Mecque et de la Mosquée du Prophète à Médine. Elles prennent en charge rapidement les malaises, la déshydratation ou les blessures légères — les motifs de consultation les plus fréquents pendant un pèlerinage.",
  },
  {
    slug: "omra-sante-2",
    articleSlug: "omra-sante",
    categorySlug: "vie-pratique",
    question: "Que faire en cas d'urgence médicale grave ?",
    answer: "Des établissements spécialisés, notamment ceux gérés par le ministère de la Santé saoudien, assurent soins intensifs et interventions chirurgicales. Nombre de ces structures fonctionnent 24 heures sur 24 à proximité immédiate des lieux saints.",
  },
  {
    slug: "omra-sante-3",
    articleSlug: "omra-sante",
    categorySlug: "vie-pratique",
    question: "Peut-on trouver facilement des médicaments courants sur place ?",
    answer: "Oui, les pharmacies sont présentes à chaque coin de rue et permettent de se procurer les médicaments courants — antidouleurs, solutions de réhydratation — sur présentation d'une ordonnance locale ou sur simple conseil du pharmacien.",
  },
  {
    slug: "omra-sante-4",
    articleSlug: "omra-sante",
    categorySlug: "vie-pratique",
    question: "Comment éviter les coups de chaleur ?",
    answer: "Boire régulièrement de l'eau, de préférence en bouteille, est le premier réflexe à adopter pour éviter l'épuisement thermique et les coups de chaleur, particulièrement fréquents compte tenu du climat et de l'effort physique que demandent certains rites.",
  },
  {
    slug: "omra-sante-5",
    articleSlug: "omra-sante",
    categorySlug: "vie-pratique",
    question: "Que dois-je emporter dans ma trousse médicale ?",
    answer: "Il est recommandé d'emporter ses ordonnances traduites, ses médicaments habituels en quantité suffisante pour toute la durée du séjour, ainsi que des masques et un désinfectant sans parfum — ce dernier point étant important pour les pèlerins en état d'ihram, soumis à l'interdiction d'utiliser des produits parfumés.",
  },
  {
    slug: "omra-sante-6",
    articleSlug: "omra-sante",
    categorySlug: "vie-pratique",
    question: "Quel numéro appeler en cas d'urgence vitale ?",
    answer: "Le 997 est le numéro d'urgence médicale en Arabie saoudite. Sur place, les agents de sécurité présents en permanence autour des lieux saints peuvent également orienter immédiatement un pèlerin en difficulté vers l'unité mobile la plus proche.",
  },
  {
    slug: "omra-shopping",
    articleSlug: "omra-shopping",
    categorySlug: "vie-pratique",
    question: "Où faire du shopping à La Mecque et à Médine pendant la Omra ?",
    answer: "La Mecque et Médine comptent toutes deux des centres commerciaux modernes, souvent à quelques pas des lieux saints. À La Mecque : Makkah Mall, Al Diyafa Mall, Abraj Al Bait Mall (au pied de la Tour de l'Horloge), Al Noor Mall et Al-Rashid Mega Mall. À Médine, le Taiba Commercial Center, situé près de la Mosquée du Prophète, reste l'adresse de référence pour les tapis de prière, les dattes, l'or et les cadeaux traditionnels à rapporter de son séjour.",
  },
  {
    slug: "mecque-001-attractions",
    articleSlug: "mecque-001-attractions",
    categorySlug: "decouvrir-mecque",
    question: "Quelles sont les meilleures attractions de La Mecque ?",
    answer: "La Mecque est avant tout le cœur spirituel de la Omra et du Hajj. Pour tout pèlerin, la première découverte reste naturellement le Masjid al-Haram et la Sainte Kaaba, autour desquels se déroulent les rites essentiels du séjour.",
  },
  {
    slug: "mecque-002-incontournables",
    articleSlug: "mecque-002-incontournables",
    categorySlug: "decouvrir-mecque",
    question: "Quels sont les incontournables d'un séjour à La Mecque, au-delà des rites de la Omra ?",
    answer: "Au-delà des rites de la Omra eux-mêmes, plusieurs expériences reviennent souvent parmi ce que les voyageurs considèrent comme incontournables lors d'un séjour à La Mecque.",
  },
  {
    slug: "mecque-003-enfants",
    articleSlug: "mecque-003-enfants",
    categorySlug: "decouvrir-mecque",
    question: "Quelles sont les meilleures activités à La Mecque avec des enfants ?",
    answer: "Voyager en famille à La Mecque reste tout à fait possible, et certaines expériences se prêtent particulièrement bien à un séjour avec des enfants.",
  },
  {
    slug: "mecque-004-plein-air",
    articleSlug: "mecque-004-plein-air",
    categorySlug: "decouvrir-mecque",
    question: "Quelles sont les meilleures activités de plein air autour de La Mecque ?",
    answer: "Pour les voyageurs qui souhaitent sortir un peu du cadre urbain pendant leur séjour, la région autour de La Mecque et Djeddah offre plusieurs possibilités.",
  },
  {
    slug: "mecque-005-petits-budgets",
    articleSlug: "mecque-005-petits-budgets",
    categorySlug: "decouvrir-mecque",
    question: "Quelles sont les meilleures activités à petit budget autour de La Mecque ?",
    answer: "Découvrir La Mecque au-delà des rites de la Omra ne demande pas nécessairement un budget important. Plusieurs musées de la ville pratiquent des tarifs d'entrée modestes, notamment le musée Wahy et le musée du Saint Coran, tous deux consacrés à l'histoire de la révélation coranique et à sa transmission à travers les siècles — une découverte accessible pour qui souhaite prolonger sa réflexion spirituelle sans dépense importante.",
  },
  {
    slug: "mecque-006-musees-expositions",
    articleSlug: "mecque-006-musees-expositions",
    categorySlug: "decouvrir-mecque",
    question: "Quels sont les musées et expositions les plus populaires à La Mecque ?",
    answer: "Plusieurs musées et espaces d'exposition, à La Mecque comme à proximité, permettent de prolonger la découverte spirituelle du séjour par une dimension historique et culturelle.",
  },
  {
    slug: "omra-decouvrir-la-mecque",
    articleSlug: "omra-decouvrir-la-mecque",
    categorySlug: "decouvrir-mecque",
    question: "Que découvrir à La Mecque pendant un séjour Omra ?",
    answer: "Tout séjour Omra s'organise autour de la Masjid al-Haram et de la Kaaba, cœur spirituel de l'islam. Mais La Mecque et ses environs comptent aussi plusieurs lieux qui éclairent l'histoire du pèlerinage : Safa et Marwa, où s'accomplit le sa'i ; Jabal al-Nour et la grotte de Hira, site de la première révélation coranique ; Jabal Thawr, refuge du Prophète ﷺ pendant la Hijra ; le mont Arafat, Muzdalifah et Mina, étapes du Hajj. La Tour de l'Horloge et son musée, l'usine de la Kiswa, les musées consacrés à la biographie du Prophète et au Saint Coran complètent la découverte culturelle, tout comme la mosquée Aïcha, la mosquée des Djinns et le système hydraulique historique d'Aïn Zoubayda.",
  },
  {
    slug: "omra-mecque-lieu-ain-zoubayda",
    articleSlug: "omra-mecque-lieu-ain-zoubayda",
    categorySlug: "decouvrir-mecque",
    question: "Qu'est-ce qu'Aïn Zoubayda ?",
    answer: "Ce système hydraulique ancien, commandé au VIIIe siècle par Zubaydah, épouse du calife Harun al-Rashid, achemina pendant des siècles l'eau vers La Mecque et ses pèlerins — un témoignage de l'ingéniosité déployée pour soutenir l'accueil des pèlerins dans une ville au climat aride.",
  },
  {
    slug: "omra-mecque-lieu-jabal-al-nour",
    articleSlug: "omra-mecque-lieu-jabal-al-nour",
    categorySlug: "decouvrir-mecque",
    question: "Qu'est-ce que Jabal al-Nour et la grotte de Hira ?",
    answer: "À la périphérie de La Mecque, le « Mont de la Lumière » abrite à son sommet la grotte où le Prophète ﷺ reçut, en l'an 610, la toute première révélation du Coran. L'ascension jusqu'à la grotte reste un moment fort pour de nombreux pèlerins, entre effort physique et recueillement.",
  },
  {
    slug: "omra-mecque-lieu-jabal-thawr",
    articleSlug: "omra-mecque-lieu-jabal-thawr",
    categorySlug: "decouvrir-mecque",
    question: "Qu'est-ce que Jabal Thawr et la grotte de Thawr ?",
    answer: "Cette montagne abrite la grotte où le Prophète ﷺ et Abu Bakr (RA) trouvèrent refuge trois jours durant au début de la Hijra, échappant à leurs poursuivants — un épisode resté comme un symbole de confiance en la protection divine.",
  },
  {
    slug: "omra-mecque-lieu-masjid-al-haram-kaaba",
    articleSlug: "omra-mecque-lieu-masjid-al-haram-kaaba",
    categorySlug: "decouvrir-mecque",
    question: "Qu'est-ce que la Masjid al-Haram et la Kaaba ?",
    answer: "Cœur spirituel de l'islam, la Grande Mosquée entoure la Kaaba, que la tradition attribue à la reconstruction par le prophète Ibrahim et son fils Ismaïl. C'est autour d'elle que les pèlerins accomplissent le tawaf, à proximité de la Pierre noire et de la source de Zamzam.",
  },
  {
    slug: "omra-mecque-lieu-mina",
    articleSlug: "omra-mecque-lieu-mina",
    categorySlug: "decouvrir-mecque",
    question: "Qu'est-ce que Mina ?",
    answer: "Surnommée la plus grande ville de tentes au monde, Mina est associée à l'épisode où Ibrahim reçut l'ordre de sacrifier son fils Ismaïl, avant que ce sacrifice ne soit remplacé par celui d'un bélier.",
  },
  {
    slug: "omra-mecque-lieu-mont-arafat",
    articleSlug: "omra-mecque-lieu-mont-arafat",
    categorySlug: "decouvrir-mecque",
    question: "Qu'est-ce que le mont Arafat (Jabal al-Rahmah) ?",
    answer: "La « Montagne de la Miséricorde » est le lieu où le Prophète ﷺ prononça son sermon d'adieu. S'y tenir constitue le pilier central du Hajj, mais le site reste chargé de sens pour tout pèlerin, même en dehors de cette période.",
  },
  {
    slug: "omra-mecque-lieu-mosquee-aicha",
    articleSlug: "omra-mecque-lieu-mosquee-aicha",
    categorySlug: "decouvrir-mecque",
    question: "Qu'est-ce que la mosquée Aïcha (Masjid al-Tan'im) ?",
    answer: "Située à une dizaine de kilomètres du centre-ville, cette mosquée doit son nom à Aïcha (RA), l'épouse du Prophète ﷺ. Elle sert aujourd'hui de point de sacralisation (miqat) le plus proche de La Mecque pour les pèlerins souhaitant accomplir une Omra supplémentaire pendant leur séjour.",
  },
  {
    slug: "omra-mecque-lieu-mosquee-djinns",
    articleSlug: "omra-mecque-lieu-mosquee-djinns",
    categorySlug: "decouvrir-mecque",
    question: "Qu'est-ce que la mosquée des Djinns ?",
    answer: "Selon la tradition rapportée dans le Coran (sourate Al-Jinn), un groupe de djinns se serait arrêté en ce lieu pour écouter le Prophète ﷺ réciter le Coran, avant de repartir convaincus embrasser l'islam.",
  },
  {
    slug: "omra-mecque-lieu-musee-international-biographie-mecque",
    articleSlug: "omra-mecque-lieu-musee-international-biographie-mecque",
    categorySlug: "decouvrir-mecque",
    question: "Que voir au Musée international de la biographie du Prophète à La Mecque ?",
    answer: "Pendant de son homologue de Médine, ce musée propose plus de 200 expositions visuelles et interactives, entre hologrammes, films documentaires et pièces historiques, pour retracer le caractère et l'enseignement du Prophète ﷺ.",
  },
  {
    slug: "omra-mecque-lieu-musee-saint-coran",
    articleSlug: "omra-mecque-lieu-musee-saint-coran",
    categorySlug: "decouvrir-mecque",
    question: "Qu'est-ce que le Musée du Saint Coran ?",
    answer: "Consacré à l'histoire de la révélation coranique et à sa transmission à travers les âges — manuscrits, calligraphie, contexte historique — ce musée prolonge naturellement la réflexion entamée à Jabal al-Nour.",
  },
  {
    slug: "omra-mecque-lieu-musee-wahy",
    articleSlug: "omra-mecque-lieu-musee-wahy",
    categorySlug: "decouvrir-mecque",
    question: "Qu'est-ce que le musée Wahy ?",
    answer: "Comme le Musée du Saint Coran, cet espace retrace l'histoire de la révélation coranique et sa transmission à travers les âges, en complément de la découverte de Jabal al-Nour.",
  },
  {
    slug: "omra-mecque-lieu-muzdalifah",
    articleSlug: "omra-mecque-lieu-muzdalifah",
    categorySlug: "decouvrir-mecque",
    question: "Qu'est-ce que Muzdalifah ?",
    answer: "Étape du parcours du Hajj entre Arafat et La Mecque, Muzdalifah est le lieu où les pèlerins font halte pour ramasser les cailloux destinés à la lapidation symbolique — un site qui aide à mieux saisir la géographie sacrée de la région, même hors saison de Hajj.",
  },
  {
    slug: "omra-mecque-lieu-safa-et-marwa",
    articleSlug: "omra-mecque-lieu-safa-et-marwa",
    categorySlug: "decouvrir-mecque",
    question: "Que représentent Safa et Marwa ?",
    answer: "Ces deux collines, intégrées à l'enceinte de la Grande Mosquée, sont le théâtre du sa'i : sept allers-retours qui commémorent la course de Hajar cherchant de l'eau pour son fils Ismaïl — une quête à l'origine, selon la tradition, de la source de Zamzam.",
  },
  {
    slug: "omra-mecque-lieu-tour-horloge",
    articleSlug: "omra-mecque-lieu-tour-horloge",
    categorySlug: "decouvrir-mecque",
    question: "Que voir à la Tour de l'Horloge de La Mecque ?",
    answer: "Dominant la Grande Mosquée du haut de ses 480 mètres, la tour abrite un musée consacré à l'astronomie et à l'histoire de La Mecque. Sa terrasse panoramique offre une vue plongeante sur la Kaaba, une perspective inédite sur un lieu que l'on découvre habituellement au ras du sol.",
  },
  {
    slug: "omra-mecque-lieu-usine-kiswa",
    articleSlug: "omra-mecque-lieu-usine-kiswa",
    categorySlug: "decouvrir-mecque",
    question: "Qu'est-ce que l'usine de la Kiswa ?",
    answer: "C'est ici qu'est confectionnée chaque année la Kiswa, l'immense étoffe de soie noire brodée de calligraphies dorées qui recouvre la Kaaba — un symbole fort de la continuité de ce rituel à travers les siècles.",
  },
  {
    slug: "medine-001-incontournables",
    articleSlug: "medine-001-incontournables",
    categorySlug: "decouvrir-medine",
    question: "Quels sont les incontournables à découvrir à Médine ?",
    answer: "À Médine, plusieurs expériences reviennent régulièrement parmi ce que les voyageurs considèrent comme incontournables, en complément du recueillement à la Mosquée du Prophète.",
  },
  {
    slug: "medine-002-enfants",
    articleSlug: "medine-002-enfants",
    categorySlug: "decouvrir-medine",
    question: "Quelles sont les meilleures activités pour les enfants à Médine ?",
    answer: "Médine se prête bien à un séjour en famille, et deux types d'expériences reviennent souvent pour les voyageurs accompagnés d'enfants.",
  },
  {
    slug: "medine-003-plein-air",
    articleSlug: "medine-003-plein-air",
    categorySlug: "decouvrir-medine",
    question: "Quelles sont les meilleures activités de plein air autour de Médine ?",
    answer: "Pour les voyageurs qui souhaitent sortir du cadre de la ville, les environs de Médine offrent plusieurs possibilités de plein air.",
  },
  {
    slug: "medine-004-musees-expositions",
    articleSlug: "medine-004-musees-expositions",
    categorySlug: "decouvrir-medine",
    question: "Quels sont les musées et expositions les plus populaires à Médine ?",
    answer: "Médine compte plusieurs espaces qui permettent de prolonger la découverte spirituelle du séjour par une dimension historique et patrimoniale.",
  },
  {
    slug: "omra-decouvrir-medine",
    articleSlug: "omra-decouvrir-medine",
    categorySlug: "decouvrir-medine",
    question: "Que découvrir à Médine pendant un séjour Omra ?",
    answer: "Après le recueillement à La Mecque, Médine offre un temps fort à part entière du séjour Omra. La Mosquée du Prophète (Al-Masjid an-Nabawi) en est le cœur, avec sa Rawdah tant recherchée par les pèlerins. Les environs comptent aussi plusieurs lieux chargés d'histoire : la mosquée de Quba, première mosquée de l'islam ; le mont Ouhud et son cimetière des martyrs ; la mosquée Al-Qiblatayn, où fut changée la direction de la prière ; les Sept Mosquées du site de la Tranchée ; et le cimetière d'Al-Baqi. Deux musées — le Musée international de la biographie du Prophète et le musée Dar Al-Madinah — permettent de prolonger la découverte, de même que la gare historique du Hedjaz. Pour les séjours plus longs, une excursion à Al-'Ula ouvre sur une tout autre facette de la région, entre archéologie et paysages spectaculaires.",
  },
  {
    slug: "omra-medine-lieu-cimetiere-al-baqi",
    articleSlug: "omra-medine-lieu-cimetiere-al-baqi",
    categorySlug: "decouvrir-medine",
    question: "Qu'est-ce que le cimetière d'Al-Baqi ?",
    answer: "Juste à côté de la Mosquée du Prophète, ce cimetière abrite les tombes de nombreux compagnons, épouses et proches du Prophète ﷺ, dont le calife Uthman ibn Affan. Il frappe par son extrême sobriété — pas de mausolées, pas d'ornements — fidèle à l'enseignement islamique sur l'humilité face à la mort.",
  },
  {
    slug: "omra-medine-lieu-elephant-rock",
    articleSlug: "omra-medine-lieu-elephant-rock",
    categorySlug: "decouvrir-medine",
    question: "Qu'est-ce qu'Elephant Rock (Jabal Al-Fil) ?",
    answer: "Sur le site d'Al-'Ula, cette formation rocheuse spectaculaire, façonnée par des millénaires d'érosion, prend la silhouette d'un éléphant dressant sa trompe. Haute d'une cinquantaine de mètres, elle est particulièrement prisée au coucher du soleil.",
  },
  {
    slug: "omra-medine-lieu-gare-hedjaz",
    articleSlug: "omra-medine-lieu-gare-hedjaz",
    categorySlug: "decouvrir-medine",
    question: "Qu'est-ce que la gare historique du Hedjaz ?",
    answer: "Vestige de l'ère ottomane, cette gare rappelle la ligne ferroviaire du Hedjaz, achevée en 1908 pour relier Damas à Médine et faciliter le pèlerinage, avant d'être en partie détruite pendant la révolte arabe. Voies, locomotives et bâtiments d'époque en font une parenthèse insolite dans la découverte de la ville.",
  },
  {
    slug: "omra-medine-lieu-hegra",
    articleSlug: "omra-medine-lieu-hegra",
    categorySlug: "decouvrir-medine",
    question: "Qu'est-ce que Hegra (Madain Saleh) ?",
    answer: "Accessible depuis Médine via une excursion à Al-'Ula, Hegra est le premier site d'Arabie saoudite inscrit au patrimoine mondial de l'UNESCO. Deuxième capitale du royaume nabatéen après Pétra, elle compte près de 94 tombeaux monumentaux sculptés à même la roche.",
  },
  {
    slug: "omra-medine-lieu-jabal-ikmah",
    articleSlug: "omra-medine-lieu-jabal-ikmah",
    categorySlug: "decouvrir-medine",
    question: "Qu'est-ce que Jabal Ikmah ?",
    answer: "Surnommée « la bibliothèque à ciel ouvert », cette montagne du site d'Al-'Ula rassemble des milliers d'inscriptions et de gravures rupestres antiques laissées par les civilisations qui ont traversé la région, bien avant l'islam.",
  },
  {
    slug: "omra-medine-lieu-maraya",
    articleSlug: "omra-medine-lieu-maraya",
    categorySlug: "decouvrir-medine",
    question: "Qu'est-ce que Maraya à Al-'Ula ?",
    answer: "Littéralement « miroirs » en arabe, Maraya est le plus grand bâtiment miroir au monde, niché dans la vallée d'Ashar. Sa façade réfléchissante le fait disparaître dans le paysage désertique, et il accueille aujourd'hui concerts et événements culturels.",
  },
  {
    slug: "omra-medine-lieu-mont-ouhud",
    articleSlug: "omra-medine-lieu-mont-ouhud",
    categorySlug: "decouvrir-medine",
    question: "Que représente le mont Ouhud pour les pèlerins ?",
    answer: "Le mont Ouhud fut le théâtre, en l'an 3 de l'Hégire, d'une des batailles fondatrices de l'islam, où soixante-dix compagnons du Prophète perdirent la vie, dont Hamza ibn Abdulmuttalib. Au pied de la montagne, le cimetière des martyrs forme aujourd'hui un lieu de recueillement sobre, où l'histoire se raconte presque en silence.",
  },
  {
    slug: "omra-medine-lieu-mosquee-al-qiblatayn",
    articleSlug: "omra-medine-lieu-mosquee-al-qiblatayn",
    categorySlug: "decouvrir-medine",
    question: "Pourquoi la mosquée Al-Qiblatayn est-elle appelée ainsi ?",
    answer: "C'est ici, en pleine prière, que le Prophète ﷺ reçut la révélation lui ordonnant de changer la direction de la Qibla, de Jérusalem vers La Mecque. Il se retourna sur-le-champ vers la nouvelle direction, entraînant toute l'assemblée avec lui — un geste qui donna son nom à la mosquée, seule à avoir un temps compté deux qiblas en son sein.",
  },
  {
    slug: "omra-medine-lieu-mosquee-de-quba",
    articleSlug: "omra-medine-lieu-mosquee-de-quba",
    categorySlug: "decouvrir-medine",
    question: "Qu'est-ce que la mosquée de Quba ?",
    answer: "Située à quelques kilomètres du centre de Médine, Quba est la toute première mosquée de l'histoire de l'islam, dont le Prophète ﷺ posa lui-même les premières pierres. Une tradition rapporte que deux unités de prière accomplies à Quba équivalent en mérite à une Omra, ce qui pousse encore aujourd'hui de nombreux pèlerins à s'y rendre le vendredi.",
  },
  {
    slug: "omra-medine-lieu-mosquee-du-prophete",
    articleSlug: "omra-medine-lieu-mosquee-du-prophete",
    categorySlug: "decouvrir-medine",
    question: "Qu'est-ce que la Mosquée du Prophète à Médine ?",
    answer: "Deuxième lieu saint de l'islam, elle fut fondée par le Prophète ﷺ lui-même dès son arrivée à Médine. Sous son emblématique dôme vert repose son tombeau, aux côtés de ceux d'Abu Bakr et Omar. Entre le minbar et la chambre du Prophète s'étend la Rawdah, « le jardin du paradis », un espace particulièrement recherché par les pèlerins pour la prière.",
  },
  {
    slug: "omra-medine-lieu-musee-dar-al-madinah",
    articleSlug: "omra-medine-lieu-musee-dar-al-madinah",
    categorySlug: "decouvrir-medine",
    question: "Qu'est-ce que le musée Dar Al-Madinah ?",
    answer: "Plus intimiste que le Musée international, ce musée patrimonial rassemble une collection privée d'objets, de manuscrits anciens, d'exemplaires historiques du Coran et de photographies retraçant l'évolution de Médine à travers les siècles.",
  },
  {
    slug: "omra-medine-lieu-musee-international-biographie-medine",
    articleSlug: "omra-medine-lieu-musee-international-biographie-medine",
    categorySlug: "decouvrir-medine",
    question: "Que voir au Musée international de la biographie du Prophète à Médine ?",
    answer: "Sur environ 35 à 40 minutes, ce musée retrace la vie du Prophète ﷺ et l'essor de la civilisation islamique à travers une scénographie immersive mêlant projections, dispositifs interactifs et mise en scène sensorielle — une expérience pensée pour tous les publics.",
  },
  {
    slug: "omra-medine-lieu-puits-de-ghars",
    articleSlug: "omra-medine-lieu-puits-de-ghars",
    categorySlug: "decouvrir-medine",
    question: "Qu'est-ce que le puits de Ghars ?",
    answer: "Parmi les sept puits historiques de Médine datant de l'époque du Prophète ﷺ, celui de Ghars, près de Quba, est l'un des plus connus : la tradition rapporte que le Prophète ﷺ y buvait lui-même. Un lieu discret qui ancre très concrètement son quotidien dans le paysage de la ville.",
  },
  {
    slug: "omra-medine-lieu-sept-mosquees",
    articleSlug: "omra-medine-lieu-sept-mosquees",
    categorySlug: "decouvrir-medine",
    question: "Que sont les Sept Mosquées de Médine ?",
    answer: "Sur le versant ouest du mont Sela', sept petites mosquées jalonnent l'endroit où les musulmans creusèrent, en l'an 5 de l'Hégire, une tranchée défensive pour protéger Médine face à la coalition des tribus assiégeantes. Chaque mosquée porte le nom d'un compagnon posté à cet endroit, à l'exception de la mosquée al-Fath, bâtie où le Prophète ﷺ avait dressé sa tente.",
  },
  {
    slug: "omra-medine-lieu-vieille-ville-medine",
    articleSlug: "omra-medine-lieu-vieille-ville-medine",
    categorySlug: "decouvrir-medine",
    question: "Que découvrir dans la vieille ville de Médine ?",
    answer: "Au-delà des sites historiques, la vieille Médine se découvre par ses ruelles : le quartier patrimonial d'Al-Maghasilah, le marché Al-Noor, et les fermes des environs où l'on partage volontiers un thé traditionnel — une immersion dans l'hospitalité et le quotidien de la ville.",
  },
];
